### PR TITLE
patch facePosLevelToId shouldn't return signed Long

### PR DESCRIPTION
**Pull request by SMazu**
Long.fromString(bin, true, 2).toSigned().toString(10) -> Long.fromString(bin, true, 2).toString(10)

// check: https://git.coolaj86.com/coolaj86/s2-geometry.js/src/branch/master/src/s2geometry.js#L480

### CODE REVIEW

**Comment by SMazu** [comment]
image
```
'use strict';
 
var S2 = require('s2-geometry').S2;
 
var lat = 40.2574448;
var lng = -111.7089464;
var level = 15;

var key = S2.latLngToKey(lat, lng, level);
// '4/032212303102210'

var id = S2.latLngToId(lat, lng, level);
// '9749618446378729472'

var id = S2.keyToId(key);
// '9749618446378729472'
```

`key` is correct, `id` is wrong

**Comment by francois-baptiste** [comment]
Yeah I agree with that fix, thank you @SMazu

**Comment by francois-baptiste** [comment]
By the way we should also use uint64 for H3 cells representation, this format helps reducing data size!

**Comment by SMazu** [comment]
awesome, can we merge this then?

**Comment by jatorre** [comment]
Happy to merge! Thank you very much.

**Comment by jatorre** [comment]
Oh going to need help

**Comment by SMazu** [comment]
hi @jatorre @francois-baptiste, is there anything still pending for merging this?

**Comment by jatorre** [comment]
Sorry is taking some time. We are working on a full rebase of jslibs to add continuos integration and other exciting things, so is taking a bit longer. But will try to push today.

**Comment by jatorre** [comment]
Should be deployed too.

**Pull request merged**
