### PR TITLE
s2-error-fixes

### PR DESCRIPTION
**Pull request by SMazu**
fix for the error mentioned here for the s2geometry lib on BQ:
https://github.com/CartoDB/bigquery-jslibs/issues/1#issuecomment-581499680

### CODE REVIEW

**Comment by francois-baptiste** [comment]
I have an error from your code:
`ReferenceError: require is not defined at UDF$1(FLOAT64, FLOAT64, NUMERIC) line 1, columns 10-11`
Any idea?

**Comment by francois-baptiste** [comment]
> I have an error from your code:
> `ReferenceError: require is not defined at UDF$1(FLOAT64, FLOAT64, NUMERIC) line 1, columns 10-11`
> Any idea?

[This was a quick fix in fact](https://github.com/SMazu/bigquery-jslibs/pull/1)

**Comment by SMazu** [comment]
thanks @francois-baptiste, i've merged your PR!

let me know if your have any other questions regarding mine.

**Comment by francois-baptiste** [comment]
@SMazu I have been looking in your merge request a little further.

When I use function `S2.fromKey` i've got an error `ReferenceError: require is not defined`

 We are near to a first working version but there still have a reference to `long.js` in the code:
`require('long');`

However we cannot load npm packages using require from JavaScript UDFs
https://stackoverflow.com/a/53314446

we should integrate https://www.npmjs.com/package/long as an external libraries.

I have created a dirty long.js integration on my forked branch
https://github.com/francois-baptiste/bigquery-data-science-229608/blob/dirty-long-js-integration/libs/s2geometry.js

**Comment by francois-baptiste** [comment]
@SMazu I just proposed to you a new [merge request](https://github.com/SMazu/bigquery-jslibs/pull/2) to your branch dealing with the long.js library and proposing a new `jslibs.s2.ST_S2` to output S2key id in hexadecimal format.

You can then easily export your tables to [`kepler.gl`](https://kepler.gl/demo) for instance !

**Comment by SMazu** [comment]
@francois-baptiste this is awesome, thanks! 😃

**Comment by jatorre** [comment]
Thanks guys. This is awesome. Will  deploy now.

**Pull request merged**
